name: HyperRogue
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v2
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: zenorogue/hyperrogue
          ref: v13.0x
          path: './hyperrogue'
      - name: Build
        run: bash ./hyperrogue-debian12/build.sh
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: hypperrogue
          path: ./hyperrogue/hyperrogue