name: Hyperrogue Linux
on:
  workflow_dispatch:
    inputs:
      projectVersion:
        description: 'Project version'     
        required: true
        default: 'v13.0x'
jobs:
  bash-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v2
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: zenorogue/hyperrogue
          ref: ${{github.event.inputs.projectVersion}}
          path: ./project
      - name: Build
        run: bash ./hyperrogue-debian12/build.sh
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: hypperrogue-${{github.event.inputs.projectVersion}}
          path: ./project/hyperrogue