name: vkQuake macOS M1
on:
  workflow_dispatch:
    inputs:
      projectVersion:
        description: 'Project version'     
        required: true
        default: '1.32.2'
jobs:
  bash-script:
    runs-on: macos-14
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v2
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Novum/vkQuake
          ref: ${{github.event.inputs.projectVersion}}
          path: ./project
      - name: Build
        run: bash ./vkQuake-M1/build.sh
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: vkQuake-${{github.event.inputs.projectVersion}}
          path: ./project/build/vkquake